### ISSUE TITLE
Make zoom-functionality in map using mouse/scrollwheel configurable

### ISSUE THREAD

**Issue by GBoot** [switchonproject/cids-custom-switchon#1]
Currently, the zooming functionality in the CIDS/SIP map using the mouse/scrollwheel is opposite compared to e.g. GoogleMaps/OpenStreetmap. In order not to break backwards compatibility the 'zoom-setting' should be configurable.

**Comment by p-a-s-c-a-l** [comment]
No further enhancements to [SIP Expert GUI](http://switchonproject.github.io/cids-custom-switchon/) for casual users planned. Please use the new [HTML5 SIP Client](http://switchonproject.github.io/sip-html5/).
