### ISSUE TITLE
Make new client release

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [switchonproject/cids-custom-switchon#122]
Make a new release of client and server and clean up all [old releases](https://github.com/switchonproject/cids-custom-switchon/wiki/SIP-Releases#sip-v1-demonstrator-obsolete---to-be-removed) from deltares server. In particular, remove the obsolete release directories and deregister the services. Remove furthermore all unused files from the htdocs directory, including leftovers from the 1st demonstrator.

Change the configuration of SIP Expert GUI and disable the auto login feature. Changes the to Meta-Data Repository shall be performed my authenticated SWITCH-ON partners only.

Update the [wiki](https://github.com/switchonproject/cids-custom-switchon/wiki/SIP-Releases) accordingly.

**Comment by p-a-s-c-a-l** [comment]
- Don't forget to copy the updated switchon database to the deltares server. See [Integration Base Instances](https://github.com/switchonproject/cids-custom-switchon/wiki/Integration-Base-Instances). 
- don't forget to copy the GRDC Resource(s) from switchon_dev to switchon and to create the new indexes (see https://github.com/switchonproject/cids-custom-switchon-server/issues/7#issuecomment-77150688)

**Comment by p-a-s-c-a-l** [comment]
GRDC Stations MULTIPOINT: 
https://gist.github.com/p-a-s-c-a-l/d298edf11727089599cc#file-grdc_stations

GRDC Stations Layer:
http://tl-tc039.xtr.deltares.nl:8080/geoserver/grdc/wms?service=WMS&version=1.1.0&request=GetMap&layers=grdc:grdcdb&styles=&bbox=-162.8829,-46.238465,177.637263,72.37&width=947&height=330&srs=EPSG:4326&format=application/openlayers

**Comment by p-a-s-c-a-l** [comment]
Depends on #124

**Comment by mscholl** [comment]
old releases are cleaned, including services and htdocs, etc., new release is done, however, auto login still available.

**Comment by p-a-s-c-a-l** [comment]
@mscholl Can you please also make a **DEV** release on switchon.cismet.de that is connected to  `http://switchon.cismet.de:9987/callserver/binary` for https://github.com/switchonproject/sip-html5/issues/53?

**Comment by p-a-s-c-a-l** [comment]
Temporarily changed the cids server the SIP Expert GUI is connecting on to to an instance on switchon.cismet.de. This allows us to insert new meta-data into the ``switchon_dev`` Meta-DB on switchon.cismet.de first before applying the changes to the published Meta-Data Master Repository on water-switch-on.eu. In consequence, changes made to the Meta-Data Repository with the Export GUI are not visible on ALPHA and BETA releases of the SIP HTML5 Client on water-switch-on.eu. Instead the DEV client ```http://switchon.cismet.de/sip-snapshot/``` can be used to review the changes.

**Comment by mscholl** [comment]
all setup for semi-automated releases is done.

**Comment by p-a-s-c-a-l** [comment]
done
