### ISSUE TITLE
Open keywords and CUAHSI

### ISSUE THREAD

**Issue by emmaladolphi** [switchonproject/cids-custom-switchon#129]
When adding data into the metadata wizard and getting to step 3 (basic) where one should enter keywords it is possible to choose between CUAHSI, INSPIRE, and open keywords. So far so good. However, the CUAHSI keywords are not exactly correct since we have extended it and call it extended CUAHSI ("X-CUAHSI"). This could perhaps be confusing if we don't change the name or add some information regarding this. It would be good to keep the terminology correct in the tool to avoid confusion. 

Ideas for correcting this: Change the name or add some sort of information box about the changes/differences.

![cuahsi vs xcuahsi](https://cloud.githubusercontent.com/assets/8414617/8426095/e8572c4a-1f0c-11e5-9f66-a88bfef8546c.jpg)

Regarding the open keywords, they are not really open. You can only choose from a scroll bar that contains keywords from batch D3.1. Since about half of the data doesn't contain open keywords (since we decided to use only x-cuahsi) the open keyword function is not representative of all the data. If we only are going to use the cuahsi perhaps it is better to just remove the open keyword function when adding data? Otherwise people using the wizard may add "open" keywords that are not really open and only apply to the data from D.3.1. if we on the other hand make the open keyword function actually open (the option to write in your own keywords), it would make the scroll bar way to big and complicated to handle. Using these keywords just as an descriptive mean could work since then they won't have a search function (avoiding the problem with synonyms etc).

The best solution would perhaps be to remove the open keyword function in its whole to avoid confusion and misrepresentation of the data.

**Comment by p-a-s-c-a-l** [comment]
@duropa @rcapell @rcnijzink @GBoot @esafa

OK. Before doing any unilateral changes, I'd like to hear the opinion of the user stories group and WP2 regarding the (CUAHSI) keywords issue.

**Comment by rcapell** [comment]
CUAHSI/X-CUAHSI: I vote for re-naming and an info box explaining how
XCUAHSI came about, including a link to the CUAHSI homepage.
Regarding the open keywords I am not quite sure. Would it be possible to
have an open text field where one can enter a free text string? Or i this
maybe already covered by a "Description" field earlier in the wizard?
Otherwise I would lean towards removal of open keywords. People should be
forced to pick at least one xcuahsi keyword in any case, so that they
cannot only enter unsearchable strings (e.g. with spelling errors).

**Comment by rcnijzink** [comment]
I agree with Rene, renaming with some additional information. Regarding the 'open' keywords, maybe it should have some sort of condition in it, before making it really open and let people be able to write their own keywords. For example: 'Are there any existing keywords that apply to the data?' And only if this is answered with 'no', you get the option to add keywords. So a bit similar to what Rene suggests, force them first to look at the existing keywords. 
I really don't know if this would work, or even be an option. I just shout some thoughts here, hope it helps.

**Comment by p-a-s-c-a-l** [comment]
@rcapell 
- I can rename the list to X-CUAHSI in both the Meta-Data Wizard and the SIP. Can you please provide a short description? The description is then shown in the "completion guide" box.
- I'll remove the keywords-open selection box from the wizard.
- Free text is covered by the description field.

**Comment by rcapell** [comment]
Description suggestion (@duropa, @rcnijzink please check and improve):

X-CUAHSI keywords build on a hierarchical keyword selection from the [hydrologic ontology] (link to http://his.cuahsi.org/ontologyfiles.html) developed by [CUAHSI] (link to https://www.cuahsi.org/), with additinal hierarchical keywords for relevant non-hydrosphere data.

Pascal, can you integrate the description also in the SIP's search window?

**Comment by p-a-s-c-a-l** [comment]
In which window?

**Comment by rcapell** [comment]
I mean the red circled one in the screenshot below. X-CUAHSI is unknown to users, a brief explanation is needed when users choose keywords to search for, I think.

![screenshot_siphtml](https://cloud.githubusercontent.com/assets/6536193/8521880/c063d95a-23e8-11e5-8465-d13b43c2c2e1.png)

**Comment by p-a-s-c-a-l** [comment]
OK, I see. 
> "X-CUAHSI keywords build on a hierarchical keyword selection from the hydrologic ontology developed by CUAHSI, with additional hierarchical keywords for relevant non-hydrosphere data."

This is a quite long sentence. ;) 
Atm, I'm not sure where to put this next to the keyword selection box without cluttering the UI.

**Comment by p-a-s-c-a-l** [comment]
@rcapell 
I've added a tool tip to the X-CUAHSI keyword list. It's shown when the user hovers the mouse over the list box, so it's should always shown before the user selects a X-CUAHSI keyword.

![x-cuahsi](https://cloud.githubusercontent.com/assets/1788226/8526170/4ade740c-2405-11e5-9894-c6794c773565.png)

**Comment by rcapell** [comment]
I think this is good for now, thanks Pascal. 
If you see an opportunity to include a reference link to CUAHSI somewhere in the future, it would still be good to add that.

**Comment by p-a-s-c-a-l** [comment]
OK
