### ISSUE TITLE
Content type ftp and tar

### ISSUE THREAD

**Issue by emmaladolphi** [switchonproject/cids-custom-switchon#133]
Many datasets link to ftp servers. When adding content type this is not an option. Neither is tar-files. At this moment these datasets can't be added. If the options ftp directory and application tar could be added in the scroll bar the problem would be solved. 

ftp isn't a part of the mime-code, however Inspire does not require mime-codes specifically so it shouldn't be a problem.

![content type](https://cloud.githubusercontent.com/assets/8414617/8517237/fe19a524-23be-11e5-88b2-03dec8ab3fd7.jpg)

**Comment by p-a-s-c-a-l** [comment]
The protocol (FTP, HTTP, ...) is not part of the content type, it can be specified separately. In case of FTP, please select *ftp-download* (see screen shot) as protocol.

I added tar mime types:
- application/gzip (Compressed tar file) for tar.gz,tgz,gz files 
- application/x-tar (Composite tar file) for .tar files 

If you need additional types, please let me know.

![protocol](https://cloud.githubusercontent.com/assets/1788226/8519887/30e5e83e-23d6-11e5-8d8a-6b4f807498cd.png)

**Comment by esafa** [comment]
Ah.. but the directory list of an ftp-catalog is neither tar nor a tgz.. it
is just a ... "directory". It isnt a file.. it is a listing of files and
subdirectories. In the ISO standard the name of the attribute is
"formatname" in free text so we could assign anything there.. Perhaps add
"other" or "ftp directory listing" or "not applicable".

@emma... you can assign the type "text" until we have a solution or
workaround.


On Mon, Jul 6, 2015 at 12:38 PM, Pascal Dihé <notifications@github.com>
wrote:

> The protocol (FTP, HTTP, ...) is not part of the content type, it can be
> specified separately. In case of FTP, please select *ftp-download* (see
> screen shot) as protocol.
>
> I added tar mime types:
>
>    - application/gzip (Compressed tar file) for tar.gz,tgz,gz files
>    - application/x-tar (Composite tar file) for .tar files
>
> If you need additional types, please let me know.
>
> [image: protocol]
> <https://cloud.githubusercontent.com/assets/1788226/8519887/30e5e83e-23d6-11e5-8d8a-6b4f807498cd.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/cids-custom-switchon/issues/133#issuecomment-118805469>
> .
>



-- 
Esa Falkenroth
mobile: 0702-104028 (intl +46702104028)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)
