### ISSUE TITLE
Collection: not necessary

### ISSUE THREAD

**Issue by emmaladolphi** [switchonproject/cids-custom-switchon#134]
The part collection in the Wizard is not required according to iso or Inspire. When asking hydrologists if they find it necessary they have replied that this option doesn't seem important.The information in collection can often be find in the title or the abstract.

The options in collection apply only to already added datasets (from D3.1), which means they are not useful as options for the new datasets. This means that a new option would need to be added for every new dataset, which would result in that the scroll bar would become very long. 

To resolve this  'Collection' should perhaps be removed.

![collection](https://cloud.githubusercontent.com/assets/8414617/8517950/f2ec4bdc-23c5-11e5-815e-4b6ad6b5bf63.jpg)

**Comment by p-a-s-c-a-l** [comment]
*Collection* is a mandatory DB field and cannot be left empty. It is needed by the "browse by category" feature in SIP HTML Client and in Expert GUI to let administrators view all resources without the need to perform further searches. If you don't want to assign a category, please select **UNCATEGORIZED**. 

![uncategorized](https://cloud.githubusercontent.com/assets/1788226/8522094/e85ff7b6-23ea-11e5-9004-d6d9e7a5ea38.png)

While **UNCATEGORIZED** resources are not shown in the [quick category selector](https://raw.githubusercontent.com/switchonproject/sip-html5/dev/res/design/export/010-categories.png) of SIP HTML Client, they are shown in the Expert GUI, which is not used by hydrologists anyway.

**Comment by p-a-s-c-a-l** [comment]
Collection is necessary.
