### ISSUE TITLE
CUAHSI gone from Wizard!

### ISSUE THREAD

**Issue by emmaladolphi** [switchonproject/cids-custom-switchon#135]
In the Additional Tags the X-Cuahsi options are gone, one can only choose between keywords-open, and keywords-INSPIRE. 

![no cuahsi](https://cloud.githubusercontent.com/assets/8414617/8518399/043be952-23ca-11e5-9799-9e3bbe3b1083.jpg)

**Comment by p-a-s-c-a-l** [comment]
Restored in new release.
