### ISSUE TITLE
Wrong Contact Information 

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [switchonproject/cids-custom-switchon#137]
@emmaladolphi @esafa

Although contact information seems not so important for our end users, it is mandatory if the license requests a citation! The default contact information (SWITCH-ON) is only applicable for repuposed dataset but not for original data. In this case, the contact information of the data provider has to be added, otherwise we might face legal problems.

![point-of-contact](https://cloud.githubusercontent.com/assets/1788226/8544313/97eabb58-24a4-11e5-805b-d4ff761910fc.png)

**Comment by esafa** [comment]
(1) We are NOT allowed to have switchon as point of contact (that would be
like stealing thousands of datasets and imply that we made them). Berit
tried the BYOD and saw this and is very worried about us pretending to be
dataset contacts

(2) We ARE allowed to have switchon as metadata point of contact.

(3) I suggest we change BYOD to say the "Metadata Point of Contact"

(4) This compliant with ISO and Inspire (reponsible party.role=metadata
point of contact).

(4) Changing to metadata point of contacts is ok from a legal perspective.
We are NOT required to provide full citation for datasets even if the
license require a citation. The citation has to be provided by the people
using the datasets rather than the organisation providing the metadata.





Den 7 jul 2015 12:34 skrev "Pascal Dihé" <notifications@github.com>:

**Comment by p-a-s-c-a-l** [comment]
"Metadata Point of Contact" is always the same (SWITCHON) and thus pretty useless information. 
Why don't we add the data provider contact information and give proper credit to the people / organisations that created and published the data? This information is just missing fore a few (new) datasets.

**Comment by esafa** [comment]
Dataset contact info is missing for ALL new datasets... we are talking
about several hundred (or thousand) entries/records. We will look at the
exact number of records tomorrow to estimate how much work it would be to
find the email adresses and names, check the emails, and edit all metadata
already entered using the  basic profile.

However, Viktor already stopped working and Emma only has two weeks left so
it is a matter of priorities... there is still work to do on the "Batches".

As a workaround, if there is not time we can leave the database as-is but
hide the contact-info in BYOD (that way nobody will accuse us of taking
credit for other peoples datasets).

Cheers,
//Esa




On Wed, Jul 8, 2015 at 4:54 PM, Pascal Dihé <notifications@github.com>
wrote:

> "Metadata Point of Contact" is always the same (SWITCHON) and thus pretty
> useless information.
> Why don't we add the data provider contact information and give proper
> credit to the people / organisations that created and published the data?
> This information is just missing fore a few (new) datasets.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/cids-custom-switchon/issues/137#issuecomment-119611845>
> .
>



-- 
Esa Falkenroth
mobile: 0702-104028 (intl +46702104028)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by emmaladolphi** [comment]
There is no time to add and edit contact information this summer. Finding and editing all missing contact information would take approx 1-3 weeks. Over 500 datasets from some 100-200 organisations are missing contact information. Each contact information would take at least 3-5 minutes, but in several cases the organisation must be contacted to provide said information. I only work two more weeks in August and still have work to do on 3 batches (G, J, K) as well as testing and correcting D3.1. The only options are to remove the contact information or find somebody than can take on this task.

**Comment by p-a-s-c-a-l** [comment]
OK. I'll hide the contact information in the HTML5 GUI.

**Comment by p-a-s-c-a-l** [comment]
see https://github.com/switchonproject/cids-custom-switchon-server/issues/42#issuecomment-120331035
