### ISSUE TITLE
Map gone

### ISSUE THREAD

**Issue by emmaladolphi** [switchonproject/cids-custom-switchon#138]
In the adding geography part in the tool, the map is gone. When adding coordinates and pressing enter the coordinates rearanges, so without map it is not possible to know if the coordinates entered are correct.

Soultion: fix the map, and make the coordinates stay put as they originally are (according to the instructions).

**Comment by p-a-s-c-a-l** [comment]
I cannot reproduce the Problem. What happens, if you select a country from the list or specify another bounding box? Perhaps your bounding box co-ordinates are non-world coordinates and thus outside the visible area? The Map is loaded from demis WMS, please verfiy that you can access http://demis.nl/WMS/wms.ashx?wms=WorldMap&VERSION=1.1.0&request=getCapabilities from your machine.

![map](https://cloud.githubusercontent.com/assets/1788226/8612730/8a676566-26d5-11e5-82c1-9ad23ac2f971.png)

**Comment by emmaladolphi** [comment]
This is how it looks when I reach step 4:
![no map](https://cloud.githubusercontent.com/assets/8414617/8613491/1624f154-26e0-11e5-9f47-6ac5a886a8d6.jpg)

This shows coordinates before and after pressing enter:
Before
![before](https://cloud.githubusercontent.com/assets/8414617/8613502/338fb15c-26e0-11e5-99fc-5bf23bc714a3.jpg)
After
![after](https://cloud.githubusercontent.com/assets/8414617/8613503/37a294ee-26e0-11e5-9768-30e19aa1834a.jpg)
I cannot access the server since it's password protected.

**Comment by p-a-s-c-a-l** [comment]
> I cannot access the server since it's password protected.

Ok, then it's most likely a network or proxy issue on your side. Please ask your network administrator to check whether access to demis.nl, Port 80 is allowed.

**Comment by emmaladolphi** [comment]
Don't think it's a network issue. Since I can reach the site, but need to verify by logging in (user and password).
![server error](https://cloud.githubusercontent.com/assets/8414617/8618246/850727aa-270c-11e5-9969-71edf08bfbd7.jpg)

**Comment by p-a-s-c-a-l** [comment]
OK. Try to rest the map configuration: 
![mapconfig](https://cloud.githubusercontent.com/assets/1788226/8619065/ee422128-2713-11e5-930d-3796c0deb7ef.png)

If that doesn't work, I have to find another background map.

**Comment by emmaladolphi** [comment]
Now it works. Thanks!
