### ISSUE TITLE
XCUAHSI Surface elevation -> Level, surface

### ISSUE THREAD

**Issue by emmaladolphi** [switchonproject/cids-custom-switchon#140]
In the XCUAHSI the tag Surface elevation is entered, however original CUAHSI already have the tag Level. Our Surface elevation data therefore need to change tag into Level, surface to follow the CUAHSI standard. Users searching for Level will not find all Level data since some are tagged with Surface elevation.

Add the tag Level, surface. Re-tag all Surface elevation into Level, surface. Remove Surface elevation from the list.

**Comment by p-a-s-c-a-l** [comment]
OK

**Comment by p-a-s-c-a-l** [comment]
resolved in https://github.com/switchonproject/cids-custom-switchon-server/issues/42
