### ISSUE TITLE
Remove the GRDC dataset from repo (svn) due to violation of licence agreement.

### ISSUE THREAD

**Issue by esafa** [switchonproject/cids-custom-switchon#143]
The datasets contains data that is not allowed to be distributed. Must be removed ASAP.
See https://github.com/switchonproject/sip-html5/issues/103

**Comment by p-a-s-c-a-l** [comment]
OK, will update the Repository asap. What a pity. Hopefully we'll reach an agreement with GRDC to be able to publish the experiment results.

**Comment by p-a-s-c-a-l** [comment]
removed
