### ISSUE TITLE
Title search

### ISSUE THREAD

**Issue by emmaladolphi** [switchonproject/cids-custom-switchon#148]
When searching at the title of a resource in BYOD, eg. 'European catchments and Rivers network system (Ecrins)', as free search, I expect to get this resource as the first hit. However, the tool puts all resources in alphabetical order, which is good for keyword search, but not when you search at the actual title. I expect to get the closest match, not other resources with similar words. 

Free search should give closest match, not alphabetical order of datasets.

![title order](https://cloud.githubusercontent.com/assets/8414617/16266506/883be3c6-3885-11e6-9ac7-b7a089aeac1d.png)

**Comment by p-a-s-c-a-l** [comment]
Server-side queries do not support ranking. Rewriting all of them is not feasible. Re-ordering of search results on client side is also not feasible as discussed here: https://github.com/switchonproject/sip-html5/issues/114#issuecomment-120721661

**Comment by p-a-s-c-a-l** [comment]
closed
