### ISSUE TITLE
Missing downloads

### ISSUE THREAD

**Issue by emmaladolphi** [switchonproject/cids-custom-switchon#150]
Many resources in the BYOD search tool have missing download links (both download icons and links at the info page). These links are correct and still work in the work batches from 2015, and have been added last summer through the expert sip GUI so the links should be there.

Why are the download links missing?

Eg. see first resource
![missing downloads](https://cloud.githubusercontent.com/assets/8414617/16267228/ec561bb2-3888-11e6-9785-0229ab6c888a.png)

**Comment by p-a-s-c-a-l** [comment]
A) In the tools column, the download icon is only shown if the resource has one or more **direct download links**. In contrast to an *order* or *information* link, the user will directly get the data (file) when he clicks on this icon.

B) On the information page of the resource (*i* icon) however, also *order* and *information* links should be shown. You are right, this is currently not the case. No link is shown for the first resource, although in the Meta-Data Repository it actually contains the following link to *order* the data: http://www.eea.europa.eu/data-and-maps/data/european-catchments-and-rivers-network/","tag

So, A is a feature and B is a bug.

**Comment by p-a-s-c-a-l** [comment]
To be addressed in https://github.com/switchonproject/sip-html5/issues/128
