### ISSUE TITLE
Troubles with editing bounding box coordinates

### ISSUE THREAD

**Issue by Bastviken** [switchonproject/cids-custom-switchon#151]
After editing coordinates under the tab geographical properties in the SIP Expert Gui (in the example below latitudes were changed from 90 deg N and S to 50 deg N and S for TRMM data) and saving the changes, the result is not visible in Byod. The changes furthermore don't seem to have been saved when reopening the resource in the Expert Gui. We expect the changes to be saved and visible when searching for the data.
![spatial edit](https://cloud.githubusercontent.com/assets/20067109/17728511/da43b8be-645f-11e6-9dfe-4cd9108f1f92.png)
![spatial edit 2](https://cloud.githubusercontent.com/assets/20067109/17728565/17eecbc2-6460-11e6-9b7c-162b2c2dc0aa.png)

**Comment by p-a-s-c-a-l** [comment]
I cannot reproduce the issue. Did you press ENTER after changing the coordinates in the input field?

![trmm](https://cloud.githubusercontent.com/assets/1788226/17763853/bca9430c-651b-11e6-843b-b8413ff63b96.gif)

**Comment by Bastviken** [comment]
No, probably not. We were not aware of that is was needed. Thanks for letting us know.

**Comment by p-a-s-c-a-l** [comment]
done
