### ISSUE TITLE
User and rights management

### ISSUE THREAD

**Issue by LenaStromback** [switchonproject/cids-custom-switchon#2]
- User management that support team or project groups, i.e. each user should be able to belong to one or more groups (Comment Martin: fortunately this is a basic feature of the cids platform, thus available out of the box)

- Functionality to pick and choose from the provided data sets and save it for a later session, as some kind of my selections. The idea here is that in the beginning of an experiment or project, the user selects some versions of data form open sources or datasets available form SWITCH ON. He would then likely want to remember exactly what hw choose and reuse and extend this selection later on. This could include extracting data for some time span or geographic areas from larger datasets.

- Share my selection of data (or selected parts) with other users in a group or project

- Viewing what other users in groups I belong to have selected.

- Rights management of the data to decide who can change the data and the available information about it.

**Comment by p-a-s-c-a-l** [comment]
No further enhancements to [SIP Expert GUI](http://switchonproject.github.io/cids-custom-switchon/) for casual users planned. Please use the new [HTML5 SIP Client](http://switchonproject.github.io/sip-html5/).

If any of the above requests is also relevant for the new HTML5 client, please join the end users group and discuss about a new [user story](https://github.com/switchonproject/sip-html5/labels/user%20story).
