### ISSUE TITLE
suggestions for additional metadata attributes

### ISSUE THREAD

**Issue by emmaladolphi** [switchonproject/cids-custom-switchon#39]
As the title suggest I think the users of this program would benefit from a couple of additional attributes, these are:

*Example of programs that can open/handle the dataset. This would make it much easier, since you then can find and perhaps download the program necessary for working/looking at the data you've downloaded.

*Version. It would be nice to know the version of the data you download, so you can check for newer version if they exist.

*Funding agency. Which are the sponsors/funders for the data, perhaps the data is subjective or tendentious?

*Format of downloaded dataset.

*Login or direct download. Perhaps this should be highlighted more.

*Citation and acknowledgement. Good if you're going to use it for non-peronal use, or publish it. 

*Information on how to decode and understand dataset. If there are manuals or intructions they could be added.

**Comment by p-a-s-c-a-l** [comment]
Obsolete. Defining new attributes makes no sense if nobody is going to provide them as part of the resource meta-data. Furthermore, the meta-data record has been reduced to a bare minim.

**Comment by esafa** [comment]
Ok. I will move a few of these to "inspiration doc" but they will probably
not be of highest prio.


On Mon, Feb 16, 2015 at 2:06 PM, Pascal Dihé <notifications@github.com>
wrote:

> Closed #39
> <https://github.com/switchonproject/cids-custom-switchon/issues/39>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/cids-custom-switchon/issues/39#event-236302267>
> .
>



-- 
Esa Falkenroth
mobile: 070-666-14-14 (intl +46706661414)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)
