### ISSUE TITLE
Data management

### ISSUE THREAD

**Issue by LenaStromback** [switchonproject/cids-custom-switchon#4]
- We found the division between the right (bound external wms/wfs services) and left panes (data available at the switch on repository?) a bit confusing. For the user we believe that there is a little difference between those. Better to have a division between generally available data and the users/projects selections. This might be clear when id the distinction is open water related data sources and data available within the SWITCH-ON repositories.

- We need upload facilities for different kinds of data. A set of first examples are available in the Water Laboratories on Google drive.

- The download functionality is very important. We did not manage have a closer look to what is available but it is important to discuss formats for time series here. I believ also here the examples on google drive can serve as an examples of interesting file formats for continutes discussion.
(Comment Martin: This depends a little bit what the exact capabilities of the SIP will be in the future and that is not completely defined yet. You're right that formats are an important point but we have to see how to address this. However, right now the SIP already provides converter functionality for the hosted data. There can be an arbitrary number of converters so it should be quite easy for you to provide one that suits your needs. )

- For experiments it is important to select subsets of existing data sets and combining them with other data sets. For instance one plausible experiment would be to compare the performance of two hydrological models for a specific time period and location. In this case the user would like to select representative time series from the models for that region for the desired time period. He would also like to select measured data from a gauging station to compare with. As the models have different geographical resolutions (i.e. grid, sub basins, point, varying resolution) the user need to define how the series can be combined.) We have expert users here so the user is assumed to know how to combine the information as long as the system can give him a relevant overview of the dataset.
(Comment Martin: This is a good point and should be taken into account when the capabilities of the SIP are defined.)

**Comment by p-a-s-c-a-l** [comment]
No further enhancements to [SIP Expert GUI](http://switchonproject.github.io/cids-custom-switchon/) for casual users planned. Please use the new [HTML5 SIP Client](http://switchonproject.github.io/sip-html5/).

If any of the above requests is also relevant for the new HTML5 client, please join the end users group and discuss about a new [user story](https://github.com/switchonproject/sip-html5/labels/user%20story).
