### ISSUE TITLE
Visualisation and further computations

### ISSUE THREAD

**Issue by LenaStromback** [switchonproject/cids-custom-switchon#5]
- Combination of time series, for instance, flow components. I.e. a time series made up by several time series. They should be shown together as one time series plot with the contributions from each of the component series visible.

- Computation and visualisation of several evaluation criteria such as Re and NSE.  (An evaluation criteria is a statistical function that shows how good a simulated time series is compared to an observed one. It is computed based on a measured time series and a simulated time series.) Many different criteria exists and a discussion is needed which are most valuable.
(Comment Martin: I'm not sure what evaluation criteria is thus I'm not sure how it will be handled SIP. Thus it would be good to have a little more info. Anyway, you're right, we have to discuss how this topic shall be addressed.)

- Computations could be made based on one single basin or the upstream area of a basins. (Different selections might be relevant for different variables, for instance discharge draining the entire upstream contributing catchments is what represents the upstream situation. The idea that prompted us to raise this issue was our experience with HYPE, where the output file that summarizes the different flow components and the driving meteorological variables contains only values pertaining to the last sub catchment, which is local. But in essence, what is important in most cases is the aggregate runoff from the entire upstream sub catchments.)

**Comment by p-a-s-c-a-l** [comment]
No further enhancements to [SIP Expert GUI](http://switchonproject.github.io/cids-custom-switchon/) for casual users planned. Please use the new [HTML5 SIP Client](http://switchonproject.github.io/sip-html5/).

If any of the above requests is also relevant for the new HTML5 client, please join the end users group and discuss about a new [user story](https://github.com/switchonproject/sip-html5/labels/user%20story).
