### ISSUE TITLE
no duplicate checking for metadata

### ISSUE THREAD

**Issue by esafa** [switchonproject/cids-custom-switchon#54]
SIM only supports limited duplicate checking. Would be good to have better duplicate detection once everybody can start enter metadata into the metadata repository.

**Comment by p-a-s-c-a-l** [comment]
No further enhancements to [SIP Expert GUI](http://switchonproject.github.io/cids-custom-switchon/) for casual users planned. Please use the new [HTML5 SIP Client](http://switchonproject.github.io/sip-html5/).

If any of the above requests is also relevant for the new HTML5 client, please join the end users group and discuss about a new [user story](https://github.com/switchonproject/sip-html5/labels/user%20story).
