### ISSUE TITLE
Bugs and minor comments

### ISSUE THREAD

**Issue by LenaStromback** [switchonproject/cids-custom-switchon#6]
- There are large problems with coordination system/projections. When trying to bind several servers using other (ESPG coded) projections, map layer items appeared to be projected wrongly and sometimes moved randomly on the map. We experienced these issues for example with data from this collection: http://www.sgu.se/sgu/sv/produkter-tjanster/kartvisare_wms.html
(Comment Martins: Indeed, this is an issue we have not experienced before. We'll have a look at it.)

-  Connected to the issue above, we had problems to display information about coordinate reference systems and data content of displayed layer items (e.g. from the Austrian example data, where we did not manage to bring up an IDF curve for a given rain gauge point) We wanted to investigate the information in the rain gauge point but, did not figure out how to do this. Tried to drag the data into the map and click on them.

- We were not able to restore tabs from the central panel (which contains the map view) once we closed them. We tried Ctrl+R and the corresponding menu item. (Answer from Martin: There are two reset buttons: The button in the "Navigator" menu which resets the "overall" layout of the application components such as the resource(s) tags, search result and the Map tab itself but not the contents of the Map tab! This is because the Map is a plugin and provides its own menu bar which is the one on the right separated by a vertical line. There you can restore the layout of the windows WITHIN the Map tab using menu entry or "CTRL-R". We know this is not an optimal solution and thus this is something we will improve in the future.)

- The system sometimes seems to get stuck and we need to restart to make it function again. (Martins comment: Well, this shouldn't happen. Unfortunately, I don't know what the reason for this could be. Anyway, if something like this happens, please provide the log file that is located in your user directory with the name "switchon_demo_log.html")

- The resources tab (under the map tab) disappeared at some point and we could not get it back. Neither restart of the system nor the reset window layout functionality worked.

- There is an efficiency problem when working with E-HYPE sub basin data. (Especially using WFS functionality). The dataset did not load.

**Comment by p-a-s-c-a-l** [comment]
No further enhancements to [SIP Expert GUI](http://switchonproject.github.io/cids-custom-switchon/) for casual users planned. Please use the new [HTML5 SIP Client](http://switchonproject.github.io/sip-html5/).

If any of the above requests is also relevant for the new HTML5 client, please join the end users group and discuss about a new [user story](https://github.com/switchonproject/sip-html5/labels/user%20story).
